# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Themes' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'AuroraIMUI', '~> 0.6.2'
  # Pods for Themes

end
