# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JMessageOCDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'JMessage', '~> 3.4.0'
  # Pods for JMessageOCDemo

end
